var searchData=
[
  ['add_20your_20introductions_20here_21_0',['Add your introductions here!',['../md__c___users_magdz_source_repos_platformy__n_e_t_articles_intro.html',1,'']]],
  ['addalbum_1',['AddAlbum',['../classplatformy___n_e_t_1_1_models_1_1_data_base_service.html#aabb6f686ba0b23485949e9aa25de8518',1,'platformy_NET::Models::DataBaseService']]],
  ['addartist_2',['AddArtist',['../classplatformy___n_e_t_1_1_models_1_1_data_base_service.html#aedd12b6af9ee6183456e99a5c5eaa9c3',1,'platformy_NET::Models::DataBaseService']]],
  ['addeventhandler_3',['AddEventHandler',['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a73471f4a6d1ca4c4fceec9ad8610f0c8',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a73471f4a6d1ca4c4fceec9ad8610f0c8',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a73471f4a6d1ca4c4fceec9ad8610f0c8',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a73471f4a6d1ca4c4fceec9ad8610f0c8',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler)']]],
  ['addstatus_4',['AddStatus',['../classplatformy___n_e_t_1_1_models_1_1_data_base_service.html#ae0fd9d94308de2d503173d198474e60e',1,'platformy_NET::Models::DataBaseService']]],
  ['addtrack_5',['AddTrack',['../classplatformy___n_e_t_1_1_models_1_1_data_base_service.html#a23c97dd7b3b3df0dfb335377edd5e832',1,'platformy_NET::Models::DataBaseService']]],
  ['addyourstatus_6',['AddYourStatus',['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_1_1_add_your_status.html#a34c5a6dcad85ec938df25fe984ab7000',1,'platformy_NET.MWM.View.AddYourStatus.AddYourStatus()'],['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_1_1_add_your_status.html',1,'platformy_NET.MWM.View.AddYourStatus']]],
  ['album_7',['Album',['../classplatformy___n_e_t_1_1_models_1_1_spot_search_1_1_album.html',1,'platformy_NET::Models::SpotSearch']]],
  ['albumrestrictionobject_8',['AlbumRestrictionObject',['../classplatformy___n_e_t_1_1_models_1_1_spot_search_1_1_album_restriction_object.html',1,'platformy_NET::Models::SpotSearch']]],
  ['albums_9',['Albums',['../classplatformy___n_e_t_1_1_models_1_1_spot_search_1_1_albums.html',1,'platformy_NET::Models::SpotSearch']]],
  ['albumview_10',['AlbumView',['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_1_1_album_view.html#af1d1f8c92a627b7975822d492c209a44',1,'platformy_NET.MWM.View.AlbumView.AlbumView()'],['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_1_1_album_view.html',1,'platformy_NET.MWM.View.AlbumView']]],
  ['albumviewmodel_11',['AlbumViewModel',['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_model_1_1_album_view_model.html',1,'platformy_NET::MWM::ViewModel']]],
  ['app_12',['App',['../classplatformy___n_e_t_1_1_app.html',1,'platformy_NET']]],
  ['artist_13',['Artist',['../classplatformy___n_e_t_1_1_models_1_1_spot_search_1_1_artist.html',1,'platformy_NET::Models::SpotSearch']]],
  ['artistest_14',['Artistest',['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_1_1_artistest.html',1,'platformy_NET::MWM::View']]],
  ['artistlistbox_5fmousedoubleclick_15',['ArtistListBox_MouseDoubleClick',['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_1_1_artist_view.html#a41fb4f0c58fb08a5b8f336102778e61d',1,'platformy_NET.MWM.View.ArtistView.ArtistListBox_MouseDoubleClick()'],['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_1_1_library_view.html#a43e2dadb001e1b689efe114c1e0172b6',1,'platformy_NET.MWM.View.LibraryView.ArtistListBox_MouseDoubleClick()']]],
  ['artists_16',['Artists',['../classplatformy___n_e_t_1_1_models_1_1_spot_search_1_1_artists.html',1,'platformy_NET::Models::SpotSearch']]],
  ['artistview_17',['ArtistView',['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_1_1_artist_view.html#af3604c3bbe08b079567ab2960501e135',1,'platformy_NET.MWM.View.ArtistView.ArtistView()'],['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_1_1_artist_view.html',1,'platformy_NET.MWM.View.ArtistView']]],
  ['artistviewmodel_18',['ArtistViewModel',['../classplatformy___n_e_t_1_1_m_w_m_1_1_view_model_1_1_artist_view_model.html',1,'platformy_NET::MWM::ViewModel']]]
];
